spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/org
    username: admin
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
