name: Build and Deploy
on:
  push:
    branches:
      - add-github-actions
      - add-home-endpoint
      - fix-deploy
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres_db:
        image: postgres
        env:
          POSTGRES_USER: xeakerinqqvyzc
          POSTGRES_PASSWORD: 9e9ecf740a857e026125535bfdc5cfae402543950fa5d531195e90efb85ad6ec
          POSTGRES_DB: dbllqdfglb4jcb
          #POSTGRES_USER: admin
          #POSTGRES_PASSWORD: admin123
          #POSTGRES_DB: org
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: 1) Checkout
      - uses: actions/checkout@v2
      - name: 2) Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: 3) Package 
        run: mvn package  

      - name: 4) Set up Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_app_name: "ywalakamar-spring-boot-crud"
          heroku_email: "barxwells@gmail.com"
          
      - name: 5) Deploy
        run: mvn clean heroku:deploy-war