name: Spring Boot CRUD Application Build
on:
  push:
    branches:
      - add-github-actions
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres_db:
        image: postgres
        env:
          POSTGRES_USER: xeakerinqqvyzc
          POSTGRES_PASSWORD: 9e9ecf740a857e026125535bfdc5cfae402543950fa5d531195e90efb85ad6ec
          POSTGRES_DB: dbllqdfglb4jcb
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: "11"
      
      - name: Heroku Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_app_name: "ywalakamar-spring-boot-crud"
          heroku_email: "barxwells@gmail.com"