name: Spring Boot CRUD Application 
on:
  push:
    branches:
      - fix-deploy-error
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres_db:
        image: postgres
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin123
          POSTGRES_DB: org
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Clean
        run: mvn clean

      - name: Package
        run: mvn package  

      - name: Set up Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_app_name: "ywalakamar-spring-boot-crud"
          heroku_email: "barxwells@gmail.com"
          
      - name: Deploy
        run: mvn heroku:deploy-war